// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  drawingId: __t.u64().primaryKey().name("drawing_id"),
  roundId: __t.u64().name("round_id"),
  roomId: __t.u64().name("room_id"),
  playerId: __t.u64().name("player_id"),
  imageUrl: __t.string().name("image_url"),
  submitted: __t.bool(),
  secondsLeft: __t.u32().name("seconds_left"),
  aiScore: __t.i32().name("ai_score"),
  aiGuess: __t.string().name("ai_guess"),
  aiRoast: __t.string().name("ai_roast"),
  roundScore: __t.i32().name("round_score"),
  scored: __t.bool(),
});
