// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  roundId: __t.u64().name("round_id"),
  roomId: __t.u64().name("room_id"),
  imageUrl: __t.string().name("image_url"),
  updatedAt: __t.timestamp().name("updated_at"),
});
