// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pointId: __t.u64().primaryKey().name("point_id"),
  roundId: __t.u64().name("round_id"),
  roomId: __t.u64().name("room_id"),
  toPlayerId: __t.u64().name("to_player_id"),
  fromPlayerId: __t.u64().name("from_player_id"),
  seq: __t.u32(),
  pts: __t.string(),
  color: __t.string(),
  size: __t.f64(),
  createdAt: __t.timestamp().name("created_at"),
});
