// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CloseGradingReducer from "./close_grading_reducer";
import CreateRoomReducer from "./create_room_reducer";
import EndGameReducer from "./end_game_reducer";
import HijackDrawReducer from "./hijack_draw_reducer";
import JoinRoomReducer from "./join_room_reducer";
import KickPlayerReducer from "./kick_player_reducer";
import NextRoundReducer from "./next_round_reducer";
import OfferReplayReducer from "./offer_replay_reducer";
import PeekDrawReducer from "./peek_draw_reducer";
import RecordScoreReducer from "./record_score_reducer";
import RecordScoreForReducer from "./record_score_for_reducer";
import ResolveReplayReducer from "./resolve_replay_reducer";
import RevealRoundReducer from "./reveal_round_reducer";
import SeedWordsReducer from "./seed_words_reducer";
import SetConfigReducer from "./set_config_reducer";
import SetHijackCanvasReducer from "./set_hijack_canvas_reducer";
import SetLiveCanvasReducer from "./set_live_canvas_reducer";
import SetSpectateReducer from "./set_spectate_reducer";
import StartGameReducer from "./start_game_reducer";
import SubmitDrawingReducer from "./submit_drawing_reducer";
import SubmitGuessReducer from "./submit_guess_reducer";
import UseSabotageReducer from "./use_sabotage_reducer";
import VoteReplayReducer from "./vote_replay_reducer";

// Import all procedure arg schemas
import * as RoastInProgressProcedure from "./roast_in_progress_procedure";
import * as ScoreDrawingProcedure from "./score_drawing_procedure";

// Import all table schema definitions
import DrawingRow from "./drawing_table";
import GuessRow from "./guess_table";
import HijackCanvasRow from "./hijack_canvas_table";
import HijackPointRow from "./hijack_point_table";
import LiveCanvasRow from "./live_canvas_table";
import PeekStrokeRow from "./peek_stroke_table";
import PlayerRow from "./player_table";
import ReplayRow from "./replay_table";
import ReplayVoteRow from "./replay_vote_table";
import RoomRow from "./room_table";
import RoundRow from "./round_table";
import SabotageRow from "./sabotage_table";
import SpectateRow from "./spectate_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  drawing: __table({
    name: 'drawing',
    indexes: [
      { accessor: 'drawing_id', name: 'drawing_drawing_id_idx_btree', algorithm: 'btree', columns: [
        'drawingId',
      ] },
      { accessor: 'player_id', name: 'drawing_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'room_id', name: 'drawing_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'round_id', name: 'drawing_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'drawing_drawing_id_key', constraint: 'unique', columns: ['drawingId'] },
    ],
  }, DrawingRow),
  guess: __table({
    name: 'guess',
    indexes: [
      { accessor: 'player_id', name: 'guess_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'guess_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, GuessRow),
  hijack_canvas: __table({
    name: 'hijack_canvas',
    indexes: [
      { accessor: 'player_id', name: 'hijack_canvas_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'hijack_canvas_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, HijackCanvasRow),
  hijack_point: __table({
    name: 'hijack_point',
    indexes: [
      { accessor: 'point_id', name: 'hijack_point_point_id_idx_btree', algorithm: 'btree', columns: [
        'pointId',
      ] },
      { accessor: 'round_id', name: 'hijack_point_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
      { accessor: 'to_player_id', name: 'hijack_point_to_player_id_idx_btree', algorithm: 'btree', columns: [
        'toPlayerId',
      ] },
    ],
    constraints: [
      { name: 'hijack_point_point_id_key', constraint: 'unique', columns: ['pointId'] },
    ],
  }, HijackPointRow),
  live_canvas: __table({
    name: 'live_canvas',
    indexes: [
      { accessor: 'player_id', name: 'live_canvas_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'room_id', name: 'live_canvas_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'live_canvas_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, LiveCanvasRow),
  peek_stroke: __table({
    name: 'peek_stroke',
    indexes: [
      { accessor: 'player_id', name: 'peek_stroke_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'room_id', name: 'peek_stroke_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'round_id', name: 'peek_stroke_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
      { accessor: 'stroke_id', name: 'peek_stroke_stroke_id_idx_btree', algorithm: 'btree', columns: [
        'strokeId',
      ] },
    ],
    constraints: [
      { name: 'peek_stroke_stroke_id_key', constraint: 'unique', columns: ['strokeId'] },
    ],
  }, PeekStrokeRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'player_id', name: 'player_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'room_id', name: 'player_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'player_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerRow),
  replay: __table({
    name: 'replay',
    indexes: [
      { accessor: 'room_id', name: 'replay_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'replay_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, ReplayRow),
  replay_vote: __table({
    name: 'replay_vote',
    indexes: [
      { accessor: 'player_id', name: 'replay_vote_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'room_id', name: 'replay_vote_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'replay_vote_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, ReplayVoteRow),
  room: __table({
    name: 'room',
    indexes: [
      { accessor: 'code', name: 'room_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'room_id', name: 'room_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'room_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'room_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, RoomRow),
  round: __table({
    name: 'round',
    indexes: [
      { accessor: 'room_id', name: 'round_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { accessor: 'round_id', name: 'round_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'round_round_id_key', constraint: 'unique', columns: ['roundId'] },
    ],
  }, RoundRow),
  sabotage: __table({
    name: 'sabotage',
    indexes: [
      { accessor: 'round_id', name: 'sabotage_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
      { accessor: 'sabotage_id', name: 'sabotage_sabotage_id_idx_btree', algorithm: 'btree', columns: [
        'sabotageId',
      ] },
      { accessor: 'to_player_id', name: 'sabotage_to_player_id_idx_btree', algorithm: 'btree', columns: [
        'toPlayerId',
      ] },
    ],
    constraints: [
      { name: 'sabotage_sabotage_id_key', constraint: 'unique', columns: ['sabotageId'] },
    ],
  }, SabotageRow),
  spectate: __table({
    name: 'spectate',
    indexes: [
      { accessor: 'room_id', name: 'spectate_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'spectate_room_id_key', constraint: 'unique', columns: ['roomId'] },
    ],
  }, SpectateRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("close_grading", CloseGradingReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("end_game", EndGameReducer),
  __reducerSchema("hijack_draw", HijackDrawReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("kick_player", KickPlayerReducer),
  __reducerSchema("next_round", NextRoundReducer),
  __reducerSchema("offer_replay", OfferReplayReducer),
  __reducerSchema("peek_draw", PeekDrawReducer),
  __reducerSchema("record_score", RecordScoreReducer),
  __reducerSchema("record_score_for", RecordScoreForReducer),
  __reducerSchema("resolve_replay", ResolveReplayReducer),
  __reducerSchema("reveal_round", RevealRoundReducer),
  __reducerSchema("seed_words", SeedWordsReducer),
  __reducerSchema("set_config", SetConfigReducer),
  __reducerSchema("set_hijack_canvas", SetHijackCanvasReducer),
  __reducerSchema("set_live_canvas", SetLiveCanvasReducer),
  __reducerSchema("set_spectate", SetSpectateReducer),
  __reducerSchema("start_game", StartGameReducer),
  __reducerSchema("submit_drawing", SubmitDrawingReducer),
  __reducerSchema("submit_guess", SubmitGuessReducer),
  __reducerSchema("use_sabotage", UseSabotageReducer),
  __reducerSchema("vote_replay", VoteReplayReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("roast_in_progress", RoastInProgressProcedure.params, RoastInProgressProcedure.returnType),
  __procedureSchema("score_drawing", ScoreDrawingProcedure.params, ScoreDrawingProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.3.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

