// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  code: __t.string(),
  hostIdentity: __t.identity().name("host_identity"),
  status: __t.string(),
  totalRounds: __t.u32().name("total_rounds"),
  currentRound: __t.u32().name("current_round"),
  wordSource: __t.string().name("word_source"),
  createdAt: __t.u64().name("created_at"),
});
