// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roundId: __t.u64().primaryKey().name("round_id"),
  roomId: __t.u64().name("room_id"),
  roundNumber: __t.u32().name("round_number"),
  word: __t.string(),
  status: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  endsAt: __t.timestamp().name("ends_at"),
});
