// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Config = __t.object("Config", {
  id: __t.u32(),
  geminiApiKey: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const Drawing = __t.object("Drawing", {
  drawingId: __t.u64(),
  roundId: __t.u64(),
  roomId: __t.u64(),
  playerId: __t.u64(),
  imageUrl: __t.string(),
  submitted: __t.bool(),
  secondsLeft: __t.u32(),
  aiScore: __t.i32(),
  aiGuess: __t.string(),
  aiRoast: __t.string(),
  roundScore: __t.i32(),
  scored: __t.bool(),
});
export type Drawing = __Infer<typeof Drawing>;

export const Player = __t.object("Player", {
  playerId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  nickname: __t.string(),
  avatarColor: __t.string(),
  isHost: __t.bool(),
  totalScore: __t.i32(),
  sabotageAvailable: __t.bool(),
  connected: __t.bool(),
  joinedAt: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const RevealTimer = __t.object("RevealTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
  roomId: __t.u64(),
});
export type RevealTimer = __Infer<typeof RevealTimer>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  code: __t.string(),
  hostIdentity: __t.identity(),
  status: __t.string(),
  totalRounds: __t.u32(),
  currentRound: __t.u32(),
  wordSource: __t.string(),
  createdAt: __t.u64(),
});
export type Room = __Infer<typeof Room>;

export const Round = __t.object("Round", {
  roundId: __t.u64(),
  roomId: __t.u64(),
  roundNumber: __t.u32(),
  word: __t.string(),
  status: __t.string(),
  startedAt: __t.u64(),
  endsAt: __t.u64(),
});
export type Round = __Infer<typeof Round>;

export const RoundTimer = __t.object("RoundTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roundId: __t.u64(),
  roomId: __t.u64(),
});
export type RoundTimer = __Infer<typeof RoundTimer>;

export const Sabotage = __t.object("Sabotage", {
  sabotageId: __t.u64(),
  roundId: __t.u64(),
  roomId: __t.u64(),
  fromPlayerId: __t.u64(),
  toPlayerId: __t.u64(),
  effect: __t.string(),
  active: __t.bool(),
  createdAt: __t.u64(),
});
export type Sabotage = __Infer<typeof Sabotage>;

export const WordBank = __t.object("WordBank", {
  wordId: __t.u64(),
  text: __t.string(),
  category: __t.option(__t.string()),
});
export type WordBank = __Infer<typeof WordBank>;

