// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as RoastInProgressProcedure from "../roast_in_progress_procedure";
import * as ScoreDrawingProcedure from "../score_drawing_procedure";

export type RoastInProgressArgs = __Infer<typeof RoastInProgressProcedure.params>;
export type RoastInProgressResult = __Infer<typeof RoastInProgressProcedure.returnType>;
export type ScoreDrawingArgs = __Infer<typeof ScoreDrawingProcedure.params>;
export type ScoreDrawingResult = __Infer<typeof ScoreDrawingProcedure.returnType>;

