// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import EndGameReducer from "../end_game_reducer";
import JoinRoomReducer from "../join_room_reducer";
import KickPlayerReducer from "../kick_player_reducer";
import NextRoundReducer from "../next_round_reducer";
import SetConfigReducer from "../set_config_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitDrawingReducer from "../submit_drawing_reducer";
import UseSabotageReducer from "../use_sabotage_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type KickPlayerParams = __Infer<typeof KickPlayerReducer>;
export type NextRoundParams = __Infer<typeof NextRoundReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitDrawingParams = __Infer<typeof SubmitDrawingReducer>;
export type UseSabotageParams = __Infer<typeof UseSabotageReducer>;

